// Code generated by counterfeiter. DO NOT EDIT.
package workerfakes

import (
	context "context"
	sync "sync"

	garden "code.cloudfoundry.org/garden"
	lager "code.cloudfoundry.org/lager"
	creds "github.com/concourse/concourse/atc/creds"
	db "github.com/concourse/concourse/atc/db"
	worker "github.com/concourse/concourse/atc/worker"
)

type FakeContainerProvider struct {
	ConstructGardenWorkerContainerStub        func(lager.Logger, db.CreatedContainer, garden.Container) (worker.Container, error)
	constructGardenWorkerContainerMutex       sync.RWMutex
	constructGardenWorkerContainerArgsForCall []struct {
		arg1 lager.Logger
		arg2 db.CreatedContainer
		arg3 garden.Container
	}
	constructGardenWorkerContainerReturns struct {
		result1 worker.Container
		result2 error
	}
	constructGardenWorkerContainerReturnsOnCall map[int]struct {
		result1 worker.Container
		result2 error
	}
	FindCreatedContainerByHandleStub        func(lager.Logger, string, int) (worker.Container, bool, error)
	findCreatedContainerByHandleMutex       sync.RWMutex
	findCreatedContainerByHandleArgsForCall []struct {
		arg1 lager.Logger
		arg2 string
		arg3 int
	}
	findCreatedContainerByHandleReturns struct {
		result1 worker.Container
		result2 bool
		result3 error
	}
	findCreatedContainerByHandleReturnsOnCall map[int]struct {
		result1 worker.Container
		result2 bool
		result3 error
	}
	FindOrCreateContainerStub        func(context.Context, lager.Logger, db.ContainerOwner, worker.ImageFetchingDelegate, db.ContainerMetadata, worker.ContainerSpec, worker.WorkerSpec, creds.VersionedResourceTypes, worker.Image) (worker.Container, error)
	findOrCreateContainerMutex       sync.RWMutex
	findOrCreateContainerArgsForCall []struct {
		arg1 context.Context
		arg2 lager.Logger
		arg3 db.ContainerOwner
		arg4 worker.ImageFetchingDelegate
		arg5 db.ContainerMetadata
		arg6 worker.ContainerSpec
		arg7 worker.WorkerSpec
		arg8 creds.VersionedResourceTypes
		arg9 worker.Image
	}
	findOrCreateContainerReturns struct {
		result1 worker.Container
		result2 error
	}
	findOrCreateContainerReturnsOnCall map[int]struct {
		result1 worker.Container
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeContainerProvider) ConstructGardenWorkerContainer(arg1 lager.Logger, arg2 db.CreatedContainer, arg3 garden.Container) (worker.Container, error) {
	fake.constructGardenWorkerContainerMutex.Lock()
	ret, specificReturn := fake.constructGardenWorkerContainerReturnsOnCall[len(fake.constructGardenWorkerContainerArgsForCall)]
	fake.constructGardenWorkerContainerArgsForCall = append(fake.constructGardenWorkerContainerArgsForCall, struct {
		arg1 lager.Logger
		arg2 db.CreatedContainer
		arg3 garden.Container
	}{arg1, arg2, arg3})
	fake.recordInvocation("ConstructGardenWorkerContainer", []interface{}{arg1, arg2, arg3})
	fake.constructGardenWorkerContainerMutex.Unlock()
	if fake.ConstructGardenWorkerContainerStub != nil {
		return fake.ConstructGardenWorkerContainerStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.constructGardenWorkerContainerReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeContainerProvider) ConstructGardenWorkerContainerCallCount() int {
	fake.constructGardenWorkerContainerMutex.RLock()
	defer fake.constructGardenWorkerContainerMutex.RUnlock()
	return len(fake.constructGardenWorkerContainerArgsForCall)
}

func (fake *FakeContainerProvider) ConstructGardenWorkerContainerCalls(stub func(lager.Logger, db.CreatedContainer, garden.Container) (worker.Container, error)) {
	fake.constructGardenWorkerContainerMutex.Lock()
	defer fake.constructGardenWorkerContainerMutex.Unlock()
	fake.ConstructGardenWorkerContainerStub = stub
}

func (fake *FakeContainerProvider) ConstructGardenWorkerContainerArgsForCall(i int) (lager.Logger, db.CreatedContainer, garden.Container) {
	fake.constructGardenWorkerContainerMutex.RLock()
	defer fake.constructGardenWorkerContainerMutex.RUnlock()
	argsForCall := fake.constructGardenWorkerContainerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeContainerProvider) ConstructGardenWorkerContainerReturns(result1 worker.Container, result2 error) {
	fake.constructGardenWorkerContainerMutex.Lock()
	defer fake.constructGardenWorkerContainerMutex.Unlock()
	fake.ConstructGardenWorkerContainerStub = nil
	fake.constructGardenWorkerContainerReturns = struct {
		result1 worker.Container
		result2 error
	}{result1, result2}
}

func (fake *FakeContainerProvider) ConstructGardenWorkerContainerReturnsOnCall(i int, result1 worker.Container, result2 error) {
	fake.constructGardenWorkerContainerMutex.Lock()
	defer fake.constructGardenWorkerContainerMutex.Unlock()
	fake.ConstructGardenWorkerContainerStub = nil
	if fake.constructGardenWorkerContainerReturnsOnCall == nil {
		fake.constructGardenWorkerContainerReturnsOnCall = make(map[int]struct {
			result1 worker.Container
			result2 error
		})
	}
	fake.constructGardenWorkerContainerReturnsOnCall[i] = struct {
		result1 worker.Container
		result2 error
	}{result1, result2}
}

func (fake *FakeContainerProvider) FindCreatedContainerByHandle(arg1 lager.Logger, arg2 string, arg3 int) (worker.Container, bool, error) {
	fake.findCreatedContainerByHandleMutex.Lock()
	ret, specificReturn := fake.findCreatedContainerByHandleReturnsOnCall[len(fake.findCreatedContainerByHandleArgsForCall)]
	fake.findCreatedContainerByHandleArgsForCall = append(fake.findCreatedContainerByHandleArgsForCall, struct {
		arg1 lager.Logger
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	fake.recordInvocation("FindCreatedContainerByHandle", []interface{}{arg1, arg2, arg3})
	fake.findCreatedContainerByHandleMutex.Unlock()
	if fake.FindCreatedContainerByHandleStub != nil {
		return fake.FindCreatedContainerByHandleStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	fakeReturns := fake.findCreatedContainerByHandleReturns
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeContainerProvider) FindCreatedContainerByHandleCallCount() int {
	fake.findCreatedContainerByHandleMutex.RLock()
	defer fake.findCreatedContainerByHandleMutex.RUnlock()
	return len(fake.findCreatedContainerByHandleArgsForCall)
}

func (fake *FakeContainerProvider) FindCreatedContainerByHandleCalls(stub func(lager.Logger, string, int) (worker.Container, bool, error)) {
	fake.findCreatedContainerByHandleMutex.Lock()
	defer fake.findCreatedContainerByHandleMutex.Unlock()
	fake.FindCreatedContainerByHandleStub = stub
}

func (fake *FakeContainerProvider) FindCreatedContainerByHandleArgsForCall(i int) (lager.Logger, string, int) {
	fake.findCreatedContainerByHandleMutex.RLock()
	defer fake.findCreatedContainerByHandleMutex.RUnlock()
	argsForCall := fake.findCreatedContainerByHandleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeContainerProvider) FindCreatedContainerByHandleReturns(result1 worker.Container, result2 bool, result3 error) {
	fake.findCreatedContainerByHandleMutex.Lock()
	defer fake.findCreatedContainerByHandleMutex.Unlock()
	fake.FindCreatedContainerByHandleStub = nil
	fake.findCreatedContainerByHandleReturns = struct {
		result1 worker.Container
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeContainerProvider) FindCreatedContainerByHandleReturnsOnCall(i int, result1 worker.Container, result2 bool, result3 error) {
	fake.findCreatedContainerByHandleMutex.Lock()
	defer fake.findCreatedContainerByHandleMutex.Unlock()
	fake.FindCreatedContainerByHandleStub = nil
	if fake.findCreatedContainerByHandleReturnsOnCall == nil {
		fake.findCreatedContainerByHandleReturnsOnCall = make(map[int]struct {
			result1 worker.Container
			result2 bool
			result3 error
		})
	}
	fake.findCreatedContainerByHandleReturnsOnCall[i] = struct {
		result1 worker.Container
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeContainerProvider) FindOrCreateContainer(arg1 context.Context, arg2 lager.Logger, arg3 db.ContainerOwner, arg4 worker.ImageFetchingDelegate, arg5 db.ContainerMetadata, arg6 worker.ContainerSpec, arg7 worker.WorkerSpec, arg8 creds.VersionedResourceTypes, arg9 worker.Image) (worker.Container, error) {
	fake.findOrCreateContainerMutex.Lock()
	ret, specificReturn := fake.findOrCreateContainerReturnsOnCall[len(fake.findOrCreateContainerArgsForCall)]
	fake.findOrCreateContainerArgsForCall = append(fake.findOrCreateContainerArgsForCall, struct {
		arg1 context.Context
		arg2 lager.Logger
		arg3 db.ContainerOwner
		arg4 worker.ImageFetchingDelegate
		arg5 db.ContainerMetadata
		arg6 worker.ContainerSpec
		arg7 worker.WorkerSpec
		arg8 creds.VersionedResourceTypes
		arg9 worker.Image
	}{arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9})
	fake.recordInvocation("FindOrCreateContainer", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9})
	fake.findOrCreateContainerMutex.Unlock()
	if fake.FindOrCreateContainerStub != nil {
		return fake.FindOrCreateContainerStub(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.findOrCreateContainerReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeContainerProvider) FindOrCreateContainerCallCount() int {
	fake.findOrCreateContainerMutex.RLock()
	defer fake.findOrCreateContainerMutex.RUnlock()
	return len(fake.findOrCreateContainerArgsForCall)
}

func (fake *FakeContainerProvider) FindOrCreateContainerCalls(stub func(context.Context, lager.Logger, db.ContainerOwner, worker.ImageFetchingDelegate, db.ContainerMetadata, worker.ContainerSpec, worker.WorkerSpec, creds.VersionedResourceTypes, worker.Image) (worker.Container, error)) {
	fake.findOrCreateContainerMutex.Lock()
	defer fake.findOrCreateContainerMutex.Unlock()
	fake.FindOrCreateContainerStub = stub
}

func (fake *FakeContainerProvider) FindOrCreateContainerArgsForCall(i int) (context.Context, lager.Logger, db.ContainerOwner, worker.ImageFetchingDelegate, db.ContainerMetadata, worker.ContainerSpec, worker.WorkerSpec, creds.VersionedResourceTypes, worker.Image) {
	fake.findOrCreateContainerMutex.RLock()
	defer fake.findOrCreateContainerMutex.RUnlock()
	argsForCall := fake.findOrCreateContainerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6, argsForCall.arg7, argsForCall.arg8, argsForCall.arg9
}

func (fake *FakeContainerProvider) FindOrCreateContainerReturns(result1 worker.Container, result2 error) {
	fake.findOrCreateContainerMutex.Lock()
	defer fake.findOrCreateContainerMutex.Unlock()
	fake.FindOrCreateContainerStub = nil
	fake.findOrCreateContainerReturns = struct {
		result1 worker.Container
		result2 error
	}{result1, result2}
}

func (fake *FakeContainerProvider) FindOrCreateContainerReturnsOnCall(i int, result1 worker.Container, result2 error) {
	fake.findOrCreateContainerMutex.Lock()
	defer fake.findOrCreateContainerMutex.Unlock()
	fake.FindOrCreateContainerStub = nil
	if fake.findOrCreateContainerReturnsOnCall == nil {
		fake.findOrCreateContainerReturnsOnCall = make(map[int]struct {
			result1 worker.Container
			result2 error
		})
	}
	fake.findOrCreateContainerReturnsOnCall[i] = struct {
		result1 worker.Container
		result2 error
	}{result1, result2}
}

func (fake *FakeContainerProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.constructGardenWorkerContainerMutex.RLock()
	defer fake.constructGardenWorkerContainerMutex.RUnlock()
	fake.findCreatedContainerByHandleMutex.RLock()
	defer fake.findCreatedContainerByHandleMutex.RUnlock()
	fake.findOrCreateContainerMutex.RLock()
	defer fake.findOrCreateContainerMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeContainerProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ worker.ContainerProvider = new(FakeContainerProvider)
